spring:
  application:
    name: turbine
    
server:
  port: 4001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
turbine:
  app-config: zuul
  cluster-name-expression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: refresh
