spring:
  application:
    name: turbine
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 0.5
    
server:
  port: 4001
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
turbine:
  app-config: zuul
  cluster-name-expression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: refresh
